name: flutter_phajay_package
description: Flutter SDK for Phajay Payment Gateway. Generate QR payments and listen for status updates using the Phajay payment API and socket events.

version: 1.1.2

homepage:  https://github.com/SorngSDL/flutter-phajay-package.git
repository:  https://github.com/SorngSDL/flutter-phajay-package.git
issue_tracker:  https://github.com/SorngSDL/flutter-phajay-package.git/issues

topics:
  - payment
  - qr
  - websocket
  - flutter
  - phajay-websocket

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.2
  socket_io_client: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter: